/* eslint-disable no-shadow */
/* eslint-disable @typescript-eslint/naming-convention */
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'plx-input-orders',
  templateUrl: './orders.component.html',
  styleUrls: ['./orders.component.scss'],
})
export class OrdersComponent implements OnInit {
  viewBy: 'Parcel ID/APN';
  public statuses = ['Placed', 'InProgress', 'OnHold', 'Completed', 'Cancelled', 'Archived'];

  orders: any[] = [
    {
      id: 1,
      alternateEmailAddress: null,
      contactId: 20,
      contact: null,
      comments: null,
      customerId: 2,
      customer: null,
      enterpriseId: null,
      closingDate: '2021-07-30T00:00:00',
      fileNumber: '1234567890-01',
      active: true,
      borrowers: null,
      buyers: null,
      sellers: null,
      properties: [
        {
          id: 0,
          enterpriseId: 0,
          active: true,
          address: {
            line1: '123 W bob st',
            line2: 'string',
            line3: 'string',
            city: 'Kissamee',
            county: {
              id: 0,
              stateId: 0,
              name: 'string',
              fipsCode: 'string',
              type: 'string',
            },
            countyId: 0,
            state: {
              id: 0,
              name: 'Florida',
              abbreviation: 'string',
              fipsCode: 'string',
            },
            stateId: 0,
            postalCode: '12345',
          },

          owners: 'string',
          parcelNumber: '123456-45',
          legalDescription: 'string',
          closingTransactionId: 0,
          typeId: PropertyType.Commercial,
          vacantLot: true,
        },
      ],
      salesOrders: [
        {
          id: 0,
          comments: 'string',
          closingTransactionId: 0,
          closingTransaction: {
            id: 0,
            alternateEmailAddress: 'string',
            contactId: 0,
            contact: {
              id: 0,
              enterpriseId: 0,
              accountId: 0,
              account: {
                id: 0,
                userId: 'string',
                typeId: AccountType.Administrator,
                name: 'string',
                emailAddress: 'string',
                active: true,
              },
              leadSourceId: 0,
              leadSource: {
                id: 0,
                name: 'string',
              },
              managerId: 0,
              billingAddress: {
                line1: 'string',
                line2: 'string',
                line3: 'string',
                city: 'string',
                county: {
                  id: 0,
                  stateId: 0,
                  name: 'string',
                  fipsCode: 'string',
                  type: 'string',
                },
                countyId: 0,
                state: {
                  id: 0,
                  name: 'string',
                  abbreviation: 'string',
                  fipsCode: 'string',
                },
                stateId: 0,
                postalCode: 'string',
              },
              shippingAddress: {
                line1: 'string',
                line2: 'string',
                line3: 'string',
                city: 'string',
                county: {
                  id: 0,
                  stateId: 0,
                  name: 'string',
                  fipsCode: 'string',
                  type: 'string',
                },
                countyId: 0,
                state: {
                  id: 0,
                  name: 'string',
                  abbreviation: 'string',
                  fipsCode: 'string',
                },
                stateId: 0,
                postalCode: 'string',
              },
              firstName: 'string',
              lastName: 'string',
              middleName: 'string',
              emailAddress: 'string',
              phoneNumber: 'string',
              department: 'string',
              title: 'string',
            },
            comments: 'string',
            customerId: 0,

            enterpriseId: 0,
            typeId: TransactionType.NewSales,
            closingDate: '2021-10-11T22:21:02.300Z',
            fileNumber: '12345',
            active: true,
            borrowers: 'string',
            buyers: 'string',
            sellers: 'string',
            properties: [
              {
                id: 0,
                enterpriseId: 0,
                active: true,
                address: {
                  line1: 'string',
                  line2: 'string',
                  line3: 'string',
                  city: 'string',
                  county: {
                    id: 0,
                    stateId: 0,
                    name: 'string',
                    fipsCode: 'string',
                    type: 'string',
                  },
                  countyId: 0,
                  state: {
                    id: 0,
                    name: 'string',
                    abbreviation: 'string',
                    fipsCode: 'string',
                  },
                  stateId: 0,
                  postalCode: 'string',
                },

                owners: 'string',
                parcelNumber: 'string',
                legalDescription: 'string',
                closingTransactionId: 0,
                vacantLot: true,
              },
            ],
          },
          enterpriseId: 0,
          typeId: SalesOrderType.Estimate,
          statusId: SalesOrderStatus.Placed,
          estimateId: 0,
          billingAddress: {
            line1: 'string',
            line2: 'string',
            line3: 'string',
            city: 'string',
            county: {
              id: 0,
              stateId: 0,
              name: 'string',
              fipsCode: 'string',
              type: 'string',
            },
            countyId: 0,
            state: {
              id: 0,
              name: 'string',
              abbreviation: 'string',
              fipsCode: 'string',
            },
            stateId: 0,
            postalCode: 'string',
          },
          shippingAddress: {
            line1: 'string',
            line2: 'string',
            line3: 'string',
            city: 'string',
            county: {
              id: 0,
              stateId: 0,
              name: 'string',
              fipsCode: 'string',
              type: 'string',
            },
            countyId: 0,
            state: {
              id: 0,
              name: 'string',
              abbreviation: 'string',
              fipsCode: 'string',
            },
            stateId: 0,
            postalCode: 'string',
          },
          orderNo: 'string',
          integrationPartnerId: 0,
          lineItems: [
            {
              id: 0,
              customerPricingAggregateId: 0,
              enterpriseId: 0,
              statusId: SalesOrderItemStatus.Canceled,
              salesOrderId: 0,
              serviceId: 0,
              service: {
                closingPhase: 0,
                updateDaysCutoff: 0,
                updateTier: 0,
                isUpdate: true,
                isUpdatable: true,
                isFlatRate: true,
                isPackageItem: true,
                isFulfillable: true,
                isSellable: true,
                partitionByParcel: true,
                id: 0,
                displayName: 'string',
                name: 'string',
                code: 'string',
                category: 'string',
                description: 'string',
                options: [
                  {
                    id: 0,
                    name: 'string',
                    description: 'string',
                    active: true,
                  },
                ],
                parentId: 0,
                price: 0,
                form: 'string',
                active: true,
              },
              estimateItemId: 0,
              shippingAddress: {
                line1: 'string',
                line2: 'string',
                line3: 'string',
                city: 'string',
                county: {
                  id: 0,
                  stateId: 0,
                  name: 'string',
                  fipsCode: 'string',
                  type: 'string',
                },
                countyId: 0,
                state: {
                  id: 0,
                  name: 'string',
                  abbreviation: 'string',
                  fipsCode: 'string',
                },
                stateId: 0,
                postalCode: 'string',
              },
              quantity: 0,
              price: 0,
              dueDate: '2021-10-11T22:21:02.300Z',
              estimatedDeliveryDate: '2021-10-11T22:21:02.300Z',
              fulfilled: true,
              fulfilledDate: '2021-10-11T22:21:02.300Z',
              invoiced: true,
              shipDate: '2021-10-11T22:21:02.300Z',
              invoiceDate: '2021-10-11T22:21:02.300Z',
              comments: 'string',
              integrationWithPartner: true,
              noHoa: true,
              propPay: true,
              voluntaryHoa: true,
              overrideSowPrice: true,
              propertyId: 0,
              parcelNumber: 'string',
              property: {
                id: 0,
                enterpriseId: 0,
                active: true,
                address: {
                  line1: 'string',
                  line2: 'string',
                  line3: 'string',
                  city: 'string',
                  county: {
                    id: 0,
                    stateId: 0,
                    name: 'string',
                    fipsCode: 'string',
                    type: 'string',
                  },
                  countyId: 0,
                  state: {
                    id: 0,
                    name: 'string',
                    abbreviation: 'string',
                    fipsCode: 'string',
                  },
                  stateId: 0,
                  postalCode: 'string',
                },
                owners: 'string',
                parcelNumber: 'string',
                legalDescription: 'string',
                closingTransactionId: 0,
                typeId: PropertyType.Commercial,
              },
              taxRate: 0,
              updateTier: 0,
            },
          ],
        },
      ],
    },
    {
      id: 1,
      alternateEmailAddress: null,
      contactId: 20,
      contact: null,
      comments: null,
      customerId: 2,
      customer: null,
      enterpriseId: null,
      closingDate: '2021-07-30T00:00:00',
      fileNumber: '1234563456-01',
      active: true,
      borrowers: null,
      buyers: null,
      sellers: null,
      properties: [
        {
          id: 0,
          enterpriseId: 0,
          active: true,
          address: {
            line1: '123 W bob st',
            line2: 'string',
            line3: 'string',
            city: 'Kissamee',
            county: {
              id: 0,
              stateId: 0,
              name: 'string',
              fipsCode: 'string',
              type: 'string',
            },
            countyId: 0,
            state: {
              id: 0,
              name: 'Florida',
              abbreviation: 'string',
              fipsCode: 'string',
            },
            stateId: 0,
            postalCode: '12345',
          },
          owners: 'string',
          parcelNumber: '123456-45',
          closingTransactionId: 0,
          typeId: PropertyType.Commercial,
        },
      ],
      salesOrders: [
        {
          id: 0,
          comments: 'string',
          closingTransactionId: 0,
          closingTransaction: {
            id: 0,
            alternateEmailAddress: 'string',
            contactId: 0,
            contact: {
              id: 0,
              enterpriseId: 0,
              accountId: 0,
              account: {
                id: 0,
                userId: 'string',
                typeId: AccountType.Administrator,
                name: 'string',
                emailAddress: 'string',
                active: true,
              },
              leadSourceId: 0,
              leadSource: {
                id: 0,
                name: 'string',
              },
              managerId: 0,
              billingAddress: {
                line1: 'string',
                line2: 'string',
                line3: 'string',
                city: 'string',
                county: {
                  id: 0,
                  stateId: 0,
                  name: 'string',
                  fipsCode: 'string',
                  type: 'string',
                },
                countyId: 0,
                state: {
                  id: 0,
                  name: 'string',
                  abbreviation: 'string',
                  fipsCode: 'string',
                },
                stateId: 0,
                postalCode: 'string',
              },
              shippingAddress: {
                line1: 'string',
                line2: 'string',
                line3: 'string',
                city: 'string',
                county: {
                  id: 0,
                  stateId: 0,
                  name: 'string',
                  fipsCode: 'string',
                  type: 'string',
                },
                countyId: 0,
                state: {
                  id: 0,
                  name: 'string',
                  abbreviation: 'string',
                  fipsCode: 'string',
                },
                stateId: 0,
                postalCode: 'string',
              },
              firstName: 'string',
              lastName: 'string',
              middleName: 'string',
              emailAddress: 'string',
              phoneNumber: 'string',
              department: 'string',
              title: 'string',
              active: true,
            },
            comments: 'string',
            customerId: 0,

            enterpriseId: 0,
            typeId: TransactionType.NewSales,
            closingDate: '2021-10-11T22:21:02.300Z',
            fileNumber: '12345',
            active: true,
            borrowers: 'string',
            buyers: 'string',
            sellers: 'string',
            properties: [
              {
                id: 0,
                enterpriseId: 0,
                active: true,
                address: {
                  line1: 'string',
                  line2: 'string',
                  line3: 'string',
                  city: 'string',
                  county: {
                    id: 0,
                    stateId: 0,
                    name: 'string',
                    fipsCode: 'string',
                    type: 'string',
                  },
                  countyId: 0,
                  state: {
                    id: 0,
                    name: 'string',
                    abbreviation: 'string',
                    fipsCode: 'string',
                  },
                  stateId: 0,
                  postalCode: 'string',
                },
                owners: 'string',
                parcelNumber: 'string',
                legalDescription: 'string',
                closingTransactionId: 0,
                vacantLot: true,
              },
            ],
          },
          enterpriseId: 0,
          typeId: SalesOrderType.Estimate,
          statusId: SalesOrderStatus.InProgress,
          estimateId: 0,
          billingAddress: {
            line1: 'string',
            line2: 'string',
            line3: 'string',
            city: 'string',
            county: {
              id: 0,
              stateId: 0,
              name: 'string',
              fipsCode: 'string',
              type: 'string',
            },
            countyId: 0,
            state: {
              id: 0,
              name: 'string',
              abbreviation: 'string',
              fipsCode: 'string',
            },
            stateId: 0,
            postalCode: 'string',
          },
          shippingAddress: {
            line1: 'string',
            line2: 'string',
            line3: 'string',
            city: 'string',
            county: {
              id: 0,
              stateId: 0,
              name: 'string',
              fipsCode: 'string',
              type: 'string',
            },
            countyId: 0,
            state: {
              id: 0,
              name: 'string',
              abbreviation: 'string',
              fipsCode: 'string',
            },
            stateId: 0,
            postalCode: 'string',
          },
          orderNo: 'string',
          integrationPartnerId: 0,

          lineItems: [
            {
              id: 0,
              customerPricingAggregateId: 0,
              enterpriseId: 0,
              statusId: SalesOrderItemStatus.New,
              salesOrderId: 0,
              serviceId: 0,
              service: {
                closingPhase: 0,
                updateDaysCutoff: 0,
                updateTier: 0,
                isUpdate: true,
                isUpdatable: true,
                isFlatRate: true,
                isPackageItem: true,
                isFulfillable: true,
                isSellable: true,
                partitionByParcel: true,
                id: 0,
                displayName: 'string',
                name: 'string',
                code: 'string',
                category: 'string',
                description: 'string',
                options: [
                  {
                    id: 0,
                    name: 'string',
                    description: 'string',
                    active: true,
                  },
                ],
                parentId: 0,
                price: 0,
                form: 'string',
                active: true,
              },
              estimateItemId: 0,
              shippingAddress: {
                line1: 'string',
                line2: 'string',
                line3: 'string',
                city: 'string',
                county: {
                  id: 0,
                  stateId: 0,
                  name: 'string',
                  fipsCode: 'string',
                  type: 'string',
                },
                countyId: 0,
                state: {
                  id: 0,
                  name: 'string',
                  abbreviation: 'string',
                  fipsCode: 'string',
                },
                stateId: 0,
                postalCode: 'string',
              },
              quantity: 0,
              price: 0,
              dueDate: '2021-10-11T22:21:02.300Z',
              estimatedDeliveryDate: '2021-10-11T22:21:02.300Z',
              fulfilled: true,
              fulfilledDate: '2021-10-11T22:21:02.300Z',
              invoiced: true,
              shipDate: '2021-10-11T22:21:02.300Z',
              invoiceDate: '2021-10-11T22:21:02.300Z',
              comments: 'string',
              integrationWithPartner: true,
              noHoa: true,
              propPay: true,
              voluntaryHoa: true,
              overrideSowPrice: true,
              propertyId: 0,
              parcelNumber: 'string',
              property: {
                id: 0,
                enterpriseId: 0,
                active: true,
                address: {
                  line1: 'string',
                  line2: 'string',
                  line3: 'string',
                  city: 'string',
                  county: {
                    id: 0,
                    stateId: 0,
                    name: 'string',
                    fipsCode: 'string',
                    type: 'string',
                  },
                  countyId: 0,
                  state: {
                    id: 0,
                    name: 'string',
                    abbreviation: 'string',
                    fipsCode: 'string',
                  },
                  stateId: 0,
                  postalCode: 'string',
                },

                owners: 'string',
                parcelNumber: 'string',
                legalDescription: 'string',
                closingTransactionId: 0,
                typeId: PropertyType.Commercial,
              },
              taxRate: 0,
            },
          ],
        },
      ],

      typeId: TransactionType.NewSales,
    },
  ];
  constructor() {}
  ngOnInit(): void {}
}

export enum PropertyType {
  Commercial = 'Commercial',
  Residential = 'Residential',
}
export enum SalesOrderItemStatus {
  New = 'New',
  Processing = 'Processing',
  Waiting = 'Waiting',
  Completed = 'Completed',
  Canceled = 'Canceled',
  OnHold = 'OnHold',
}
export enum SalesOrderStatus {
  Placed = 'Placed',
  InProgress = 'InProgress',
  OnHold = 'OnHold',
  Completed = 'Completed',
  Cancelled = 'Cancelled',
  Archived = 'Archived',
}
export enum TransactionType {
  NewSales = 'NewSales',
  Refinance = 'Refinance',
  Other = 'Other',
}
export enum AccountType {
  None = 'None',
  System = 'System',
  Administrator = 'Administrator',
  Employee = 'Employee',
  User = 'User',
}
export enum SalesOrderType {
  RegularOrder = 'RegularOrder',
  Estimate = 'Estimate',
  BlanketOrder = 'BlanketOrder',
}
